import { colors } from '../../../../constants/color';
export const style = {
  heading: {
    marginTop: '40px',
    textAlign: 'center',
    fontSize: '22px',
    letterSpacing: '2px',
    fontWeight: '300',
    color: colors.primaryColor,
  },

  main: {
    paddingTop: '50px',
  },
  input: {
    fontSize:'14px',
     height: '40px',
     width: '100%',
     outline: 'none',
    border: "1px solid #d7dde2",
    borderRadius: "5px",
    marginTop: '10px',
    outline: 'none',
    backgroundColor:'#f6f6f6',
  },
  menu1: {
    fontSize:'14px',
    marginTop: '20px',
    height: '40px',
    width: '100%',
    outline: 'none',
    border: "1px solid #d7dde2",
    borderRadius: "5px",
    marginTop: '10px',
    backgroundColor:'#f6f6f6',
    color: 'grey',

  },
  menu2: {
    fontSize:'14px',
    marginTop: '20px',
    marginLeft: '7px',
    height: '40px',
    width: '100%',
    border: "1px solid #d7dde2",
    borderRadius: "5px",
    marginTop: '10px',
    outline: 'none',
    backgroundColor:'#f6f6f6',
    color:'grey',
  },
  option: {
    fontSize: '16px',
    marginTop: '15px',
    height: '150px',
    borderRadius: "5px",
    border: "1px solid #d7dde2",
    width: '100%',
    outline: 'none',
    color: 'grey',
    backgroundColor:'#f6f6f6',

  },
  contact: {
    marginTop: '20px',
    backgroundColor: colors.secondryColor,
    color: '#fff',
    letterSpacing: '2px',
    fontWeight: '400',
    borderRadius: '25px',
    border: 'none',
    padding: '13px 29px 13px 29px',
    fontSize: '14px',
    lineHeight: '17px',
    outline: 'none',
  },
  slider: {
    marginBottom: '50px',
  },
};
